### ISSUE TITLE
Custom plist file

### ISSUE THREAD

**Issue by koichirose** [nst/ScreenTime#1]
Hi,

I tried adding a custom plist file in ~/Library/Preferences/ScreenTime.plist.
I'm not sure if this is the right syntax (I copied it from other plist files), I tried quitting and restarting ScreenTime but it's still taking screenshots every minute.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>SecondsBetweenScreenshots</key>
    <integer>600</integer>
</dict>
</plist>
```

**Comment by umaar** [comment]
@nst having an example `ScreenTime.plist` file would be useful here, thanks!

**Comment by nst** [comment]
The file should be named `~/Library/Preferences/ch.seriot.ScreenTime.plist` in fact.

I updated the web page. Now, does it work?

**Comment by koichirose** [comment]
I can confirm this works with my syntax.

Thanks.
